name: Test CI/CD

on: push

jobs:
  test:
    name: "Lint & Test"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Build 🏗️
        run: echo "Done"
